#include "codegen.hpp"
#include <iostream>
#include <stdexcept>

namespace srlc {

void Codegen::indent() {
    for (int i = 0; i < indentLevel_; ++i) {
        out_ << "    ";
    }
}

std::string Codegen::generate(const std::vector<srl::StmtPtr>& statements) {
    out_.str("");
    out_.clear();

    out_ << "// ==========================================================\n";
    out_ << "// SRL (Serial Run Language) - Generated Native C++ Source   \n";
    out_ << "// Generated by srlc (SRL Standalone Ahead-of-Time Compiler) \n";
    out_ << "// ==========================================================\n\n";

    out_ << "#include \"value.hpp\"\n";
    out_ << "#include \"dsp.hpp\"\n";
    out_ << "#include \"tui.hpp\"\n";
    out_ << "#include <iostream>\n";
    out_ << "#include <vector>\n";
    out_ << "#include <string>\n";
    out_ << "#include <unordered_map>\n";
    out_ << "#include <memory>\n";
    out_ << "#include <cmath>\n";
    out_ << "#include <thread>\n";
    out_ << "#include <chrono>\n\n";

    out_ << "using namespace srl;\n\n";

    out_ << "// Runtime Helpers\n";
    out_ << "static VM g_vm;\n\n";

    out_ << "static Value srl_call_native(const std::string& name, const std::vector<Value>& args) {\n";
    out_ << "    Value fnVal;\n";
    out_ << "    if (g_vm.getEnvironment().getGlobal(name, fnVal) && fnVal.isNativeFn()) {\n";
    out_ << "        return fnVal.asNativeFn()(static_cast<int>(args.size()), args.data());\n";
    out_ << "    }\n";
    out_ << "    return Value();\n";
    out_ << "}\n\n";

    out_ << "static Value srl_add(const Value& a, const Value& b) {\n";
    out_ << "    if (a.isNumber() && b.isNumber()) return Value(a.asNumber() + b.asNumber());\n";
    out_ << "    if (a.isString() || b.isString()) return Value(a.toString() + b.toString());\n";
    out_ << "    return Value(0.0);\n";
    out_ << "}\n\n";

    out_ << "static Value srl_sub(const Value& a, const Value& b) {\n";
    out_ << "    if (a.isNumber() && b.isNumber()) return Value(a.asNumber() - b.asNumber());\n";
    out_ << "    return Value(0.0);\n";
    out_ << "}\n\n";

    out_ << "static Value srl_mul(const Value& a, const Value& b) {\n";
    out_ << "    if (a.isNumber() && b.isNumber()) return Value(a.asNumber() * b.asNumber());\n";
    out_ << "    return Value(0.0);\n";
    out_ << "}\n\n";

    out_ << "static Value srl_div(const Value& a, const Value& b) {\n";
    out_ << "    if (a.isNumber() && b.isNumber() && b.asNumber() != 0) return Value(a.asNumber() / b.asNumber());\n";
    out_ << "    return Value(0.0);\n";
    out_ << "}\n\n";

    // Separate function/struct declarations from main statements
    std::vector<const srl::Stmt*> topStatements;

    for (const auto& stmt : statements) {
        if (stmt->getType() == srl::ASTNodeType::FUNCTION_STMT) {
            emitStmt(stmt.get());
            out_ << "\n";
        } else if (stmt->getType() == srl::ASTNodeType::STRUCT_STMT) {
            emitStmt(stmt.get());
            out_ << "\n";
        } else {
            topStatements.push_back(stmt.get());
        }
    }

    out_ << "int main(int argc, char** argv) {\n";
    indentLevel_ = 1;

    for (const auto* stmt : topStatements) {
        indent();
        emitStmt(stmt);
        out_ << "\n";
    }

    indent();
    out_ << "return 0;\n";
    out_ << "}\n";

    return out_.str();
}

void Codegen::emitStmt(const srl::Stmt* stmt) {
    if (!stmt) return;

    switch (stmt->getType()) {
        case srl::ASTNodeType::EXPRESSION_STMT: {
            auto exprStmt = static_cast<const srl::ExpressionStmt*>(stmt);
            emitExpr(exprStmt->expression.get());
            out_ << ";";
            break;
        }

        case srl::ASTNodeType::VAR_STMT: {
            auto varStmt = static_cast<const srl::VarStmt*>(stmt);
            out_ << "Value " << varStmt->name.lexeme << " = ";
            if (varStmt->initializer) {
                emitExpr(varStmt->initializer.get());
            } else {
                out_ << "Value()";
            }
            out_ << ";";
            break;
        }

        case srl::ASTNodeType::BLOCK_STMT: {
            auto blockStmt = static_cast<const srl::BlockStmt*>(stmt);
            out_ << "{\n";
            indentLevel_++;
            for (const auto& s : blockStmt->statements) {
                indent();
                emitStmt(s.get());
                out_ << "\n";
            }
            indentLevel_--;
            indent();
            out_ << "}";
            break;
        }

        case srl::ASTNodeType::IF_STMT: {
            auto ifStmt = static_cast<const srl::IfStmt*>(stmt);
            out_ << "if ((";
            emitExpr(ifStmt->condition.get());
            out_ << ").isTruthy()) ";
            emitStmt(ifStmt->thenBranch.get());
            if (ifStmt->elseBranch) {
                out_ << " else ";
                emitStmt(ifStmt->elseBranch.get());
            }
            break;
        }

        case srl::ASTNodeType::WHILE_STMT: {
            auto whileStmt = static_cast<const srl::WhileStmt*>(stmt);
            out_ << "while ((";
            emitExpr(whileStmt->condition.get());
            out_ << ").isTruthy()) ";
            emitStmt(whileStmt->body.get());
            break;
        }

        case srl::ASTNodeType::RETURN_STMT: {
            auto retStmt = static_cast<const srl::ReturnStmt*>(stmt);
            out_ << "return ";
            if (retStmt->value) {
                emitExpr(retStmt->value.get());
            } else {
                out_ << "Value()";
            }
            out_ << ";";
            break;
        }

        case srl::ASTNodeType::FUNCTION_STMT: {
            auto fnStmt = static_cast<const srl::FunctionStmt*>(stmt);
            out_ << "Value " << fnStmt->name.lexeme << "(";
            for (size_t i = 0; i < fnStmt->params.size(); ++i) {
                out_ << "Value " << fnStmt->params[i].lexeme;
                if (i + 1 < fnStmt->params.size()) out_ << ", ";
            }
            out_ << ") {\n";
            indentLevel_++;
            for (const auto& s : fnStmt->body) {
                indent();
                emitStmt(s.get());
                out_ << "\n";
            }
            indent();
            out_ << "return Value();\n";
            indentLevel_--;
            out_ << "}\n";
            break;
        }

        case srl::ASTNodeType::STRUCT_STMT: {
            auto structStmt = static_cast<const srl::StructStmt*>(stmt);
            out_ << "Value " << structStmt->name.lexeme << "(";
            for (size_t i = 0; i < structStmt->fields.size(); ++i) {
                out_ << "Value " << structStmt->fields[i].lexeme;
                if (i + 1 < structStmt->fields.size()) out_ << ", ";
            }
            out_ << ") {\n";
            indentLevel_++;
            indent();
            out_ << "Value obj = srl_call_native(\"map_new\", {});\n";
            for (const auto& f : structStmt->fields) {
                indent();
                out_ << "srl_call_native(\"map_set\", {obj, Value(\"" << f.lexeme << "\"), " << f.lexeme << "});\n";
            }
            indent();
            out_ << "return obj;\n";
            indentLevel_--;
            out_ << "}\n";
            break;
        }

        default:
            break;
    }
}

void Codegen::emitExpr(const srl::Expr* expr) {
    if (!expr) return;

    switch (expr->getType()) {
        case srl::ASTNodeType::LITERAL_EXPR: {
            auto lit = static_cast<const srl::LiteralExpr*>(expr);
            if (lit->value.isNil()) {
                out_ << "Value()";
            } else if (lit->value.isBool()) {
                out_ << "Value(" << (lit->value.asBool() ? "true" : "false") << ")";
            } else if (lit->value.isNumber()) {
                out_ << "Value(" << lit->value.asNumber() << ")";
            } else if (lit->value.isString()) {
                out_ << "Value(std::string(\"" << lit->value.asString() << "\"))";
            } else {
                out_ << "Value()";
            }
            break;
        }

        case srl::ASTNodeType::VARIABLE_EXPR: {
            auto varExpr = static_cast<const srl::VariableExpr*>(expr);
            out_ << varExpr->name.lexeme;
            break;
        }

        case srl::ASTNodeType::ASSIGN_EXPR: {
            auto assignExpr = static_cast<const srl::AssignExpr*>(expr);
            out_ << "(" << assignExpr->name.lexeme << " = ";
            emitExpr(assignExpr->value.get());
            out_ << ")";
            break;
        }

        case srl::ASTNodeType::BINARY_EXPR: {
            auto bin = static_cast<const srl::BinaryExpr*>(expr);
            if (bin->op.lexeme == "+") {
                out_ << "srl_add(";
                emitExpr(bin->left.get());
                out_ << ", ";
                emitExpr(bin->right.get());
                out_ << ")";
            } else if (bin->op.lexeme == "-") {
                out_ << "srl_sub(";
                emitExpr(bin->left.get());
                out_ << ", ";
                emitExpr(bin->right.get());
                out_ << ")";
            } else if (bin->op.lexeme == "*") {
                out_ << "srl_mul(";
                emitExpr(bin->left.get());
                out_ << ", ";
                emitExpr(bin->right.get());
                out_ << ")";
            } else if (bin->op.lexeme == "/") {
                out_ << "srl_div(";
                emitExpr(bin->left.get());
                out_ << ", ";
                emitExpr(bin->right.get());
                out_ << ")";
            } else if (bin->op.lexeme == "<") {
                out_ << "Value((";
                emitExpr(bin->left.get());
                out_ << ").asNumber() < (";
                emitExpr(bin->right.get());
                out_ << ").asNumber())";
            } else if (bin->op.lexeme == ">") {
                out_ << "Value((";
                emitExpr(bin->left.get());
                out_ << ").asNumber() > (";
                emitExpr(bin->right.get());
                out_ << ").asNumber())";
            } else if (bin->op.lexeme == "==") {
                out_ << "Value((";
                emitExpr(bin->left.get());
                out_ << ") == (";
                emitExpr(bin->right.get());
                out_ << "))";
            } else {
                emitExpr(bin->left.get());
                out_ << " " << bin->op.lexeme << " ";
                emitExpr(bin->right.get());
            }
            break;
        }

        case srl::ASTNodeType::UNARY_EXPR: {
            auto un = static_cast<const srl::UnaryExpr*>(expr);
            if (un->op.lexeme == "-") {
                out_ << "Value(-(";
                emitExpr(un->right.get());
                out_ << ").asNumber())";
            } else if (un->op.lexeme == "!") {
                out_ << "Value(!(";
                emitExpr(un->right.get());
                out_ << ").isTruthy())";
            }
            break;
        }

        case srl::ASTNodeType::CALL_EXPR: {
            auto call = static_cast<const srl::CallExpr*>(expr);
            if (call->callee->getType() == srl::ASTNodeType::VARIABLE_EXPR) {
                auto varCallee = static_cast<const srl::VariableExpr*>(call->callee.get());
                std::string fnName = varCallee->name.lexeme;

                out_ << "srl_call_native(\"" << fnName << "\", {";
                for (size_t i = 0; i < call->arguments.size(); ++i) {
                    emitExpr(call->arguments[i].get());
                    if (i + 1 < call->arguments.size()) out_ << ", ";
                }
                out_ << "})";
            } else {
                emitExpr(call->callee.get());
                out_ << "(";
                for (size_t i = 0; i < call->arguments.size(); ++i) {
                    emitExpr(call->arguments[i].get());
                    if (i + 1 < call->arguments.size()) out_ << ", ";
                }
                out_ << ")";
            }
            break;
        }

        default:
            break;
    }
}

} // namespace srlc
