#include "llvm_codegen.hpp"
#include <iostream>
#include <iomanip>

namespace srlc {

std::string LLVMCodegen::newRegister() {
    return "%t" + std::to_string(++tempRegCount_);
}

std::string LLVMCodegen::newLabel(const std::string& prefix) {
    return prefix + "_" + std::to_string(++labelCount_);
}

void LLVMCodegen::emitHeader() {
    out_ << "; ==========================================================\n";
    out_ << "; SRL (Serial Run Language) - Generated LLVM IR Assembly    \n";
    out_ << "; Generated by srlc (LLVM IR Direct Machine Code Engine)   \n";
    out_ << "; ==========================================================\n\n";

    out_ << "target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n";
    out_ << "target triple = \"x86_64-pc-windows-msvc\"\n\n";

    out_ << "%struct.Value = type opaque\n\n";

    out_ << "declare %struct.Value* @srl_val_nil()\n";
    out_ << "declare %struct.Value* @srl_val_num(double)\n";
    out_ << "declare %struct.Value* @srl_val_str(i8*)\n";
    out_ << "declare %struct.Value* @srl_val_bool(i32)\n";
    out_ << "declare %struct.Value* @srl_add(%struct.Value*, %struct.Value*)\n";
    out_ << "declare %struct.Value* @srl_sub(%struct.Value*, %struct.Value*)\n";
    out_ << "declare %struct.Value* @srl_mul(%struct.Value*, %struct.Value*)\n";
    out_ << "declare %struct.Value* @srl_div(%struct.Value*, %struct.Value*)\n";
    out_ << "declare %struct.Value* @srl_call_native(i8*, i32, %struct.Value**)\n";
    out_ << "declare i32 @srl_is_truthy(%struct.Value*)\n\n";
}

std::string LLVMCodegen::generate(const std::vector<srl::StmtPtr>& statements) {
    out_.str("");
    out_.clear();
    tempRegCount_ = 0;
    labelCount_ = 0;

    emitHeader();

    // Collect functions and struct declarations
    std::vector<const srl::Stmt*> topStatements;

    for (const auto& stmt : statements) {
        if (stmt->getType() == srl::ASTNodeType::FUNCTION_STMT) {
            emitStmt(stmt.get());
            out_ << "\n";
        } else if (stmt->getType() == srl::ASTNodeType::STRUCT_STMT) {
            emitStmt(stmt.get());
            out_ << "\n";
        } else {
            topStatements.push_back(stmt.get());
        }
    }

    out_ << "define i32 @main() {\n";
    out_ << "entry:\n";

    for (const auto* stmt : topStatements) {
        emitStmt(stmt);
    }

    out_ << "    ret i32 0\n";
    out_ << "}\n";

    return out_.str();
}

void LLVMCodegen::emitStmt(const srl::Stmt* stmt) {
    if (!stmt) return;

    switch (stmt->getType()) {
        case srl::ASTNodeType::EXPRESSION_STMT: {
            auto exprStmt = static_cast<const srl::ExpressionStmt*>(stmt);
            emitExpr(exprStmt->expression.get());
            break;
        }

        case srl::ASTNodeType::VAR_STMT: {
            auto varStmt = static_cast<const srl::VarStmt*>(stmt);
            std::string initReg = varStmt->initializer ? emitExpr(varStmt->initializer.get()) : "call %struct.Value* @srl_val_nil()";
            out_ << "    %" << varStmt->name.lexeme << ".ptr = alloca %struct.Value*\n";
            out_ << "    store %struct.Value* " << initReg << ", %struct.Value** %" << varStmt->name.lexeme << ".ptr\n";
            break;
        }

        case srl::ASTNodeType::BLOCK_STMT: {
            auto blockStmt = static_cast<const srl::BlockStmt*>(stmt);
            for (const auto& s : blockStmt->statements) {
                emitStmt(s.get());
            }
            break;
        }

        case srl::ASTNodeType::IF_STMT: {
            auto ifStmt = static_cast<const srl::IfStmt*>(stmt);
            std::string condReg = emitExpr(ifStmt->condition.get());
            std::string truthReg = newRegister();
            out_ << "    " << truthReg << " = call i32 @srl_is_truthy(%struct.Value* " << condReg << ")\n";

            std::string cmpReg = newRegister();
            out_ << "    " << cmpReg << " = icmp ne i32 " << truthReg << ", 0\n";

            std::string thenLabel = newLabel("if.then");
            std::string elseLabel = newLabel("if.else");
            std::string endLabel = newLabel("if.end");

            out_ << "    br i1 " << cmpReg << ", label %" << thenLabel << ", label %" << (ifStmt->elseBranch ? elseLabel : endLabel) << "\n\n";

            out_ << thenLabel << ":\n";
            emitStmt(ifStmt->thenBranch.get());
            out_ << "    br label %" << endLabel << "\n\n";

            if (ifStmt->elseBranch) {
                out_ << elseLabel << ":\n";
                emitStmt(ifStmt->elseBranch.get());
                out_ << "    br label %" << endLabel << "\n\n";
            }

            out_ << endLabel << ":\n";
            break;
        }

        case srl::ASTNodeType::WHILE_STMT: {
            auto whileStmt = static_cast<const srl::WhileStmt*>(stmt);
            std::string condLabel = newLabel("while.cond");
            std::string bodyLabel = newLabel("while.body");
            std::string endLabel  = newLabel("while.end");

            out_ << "    br label %" << condLabel << "\n\n";
            out_ << condLabel << ":\n";
            std::string condReg = emitExpr(whileStmt->condition.get());
            std::string truthReg = newRegister();
            out_ << "    " << truthReg << " = call i32 @srl_is_truthy(%struct.Value* " << condReg << ")\n";
            std::string cmpReg = newRegister();
            out_ << "    " << cmpReg << " = icmp ne i32 " << truthReg << ", 0\n";
            out_ << "    br i1 " << cmpReg << ", label %" << bodyLabel << ", label %" << endLabel << "\n\n";

            out_ << bodyLabel << ":\n";
            emitStmt(whileStmt->body.get());
            out_ << "    br label %" << condLabel << "\n\n";

            out_ << endLabel << ":\n";
            break;
        }

        case srl::ASTNodeType::RETURN_STMT: {
            auto retStmt = static_cast<const srl::ReturnStmt*>(stmt);
            std::string valReg = retStmt->value ? emitExpr(retStmt->value.get()) : "call %struct.Value* @srl_val_nil()";
            out_ << "    ret %struct.Value* " << valReg << "\n";
            break;
        }

        case srl::ASTNodeType::FUNCTION_STMT: {
            auto fnStmt = static_cast<const srl::FunctionStmt*>(stmt);
            out_ << "define %struct.Value* @" << fnStmt->name.lexeme << "(";
            for (size_t i = 0; i < fnStmt->params.size(); ++i) {
                out_ << "%struct.Value* %" << fnStmt->params[i].lexeme;
                if (i + 1 < fnStmt->params.size()) out_ << ", ";
            }
            out_ << ") {\n";
            out_ << "entry:\n";
            for (const auto& s : fnStmt->body) {
                emitStmt(s.get());
            }
            out_ << "    %nil_default = call %struct.Value* @srl_val_nil()\n";
            out_ << "    ret %struct.Value* %nil_default\n";
            out_ << "}\n";
            break;
        }

        case srl::ASTNodeType::STRUCT_STMT: {
            auto structStmt = static_cast<const srl::StructStmt*>(stmt);
            out_ << "define %struct.Value* @" << structStmt->name.lexeme << "(";
            for (size_t i = 0; i < structStmt->fields.size(); ++i) {
                out_ << "%struct.Value* %" << structStmt->fields[i].lexeme;
                if (i + 1 < structStmt->fields.size()) out_ << ", ";
            }
            out_ << ") {\n";
            out_ << "entry:\n";
            out_ << "    %obj = call %struct.Value* @srl_call_native(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @.str.map_new, i64 0, i64 0), i32 0, %struct.Value** null)\n";
            out_ << "    ret %struct.Value* %obj\n";
            out_ << "}\n";
            break;
        }

        default:
            break;
    }
}

std::string LLVMCodegen::emitExpr(const srl::Expr* expr) {
    if (!expr) return "call %struct.Value* @srl_val_nil()";

    switch (expr->getType()) {
        case srl::ASTNodeType::LITERAL_EXPR: {
            auto lit = static_cast<const srl::LiteralExpr*>(expr);
            std::string reg = newRegister();
            if (lit->value.isNil()) {
                out_ << "    " << reg << " = call %struct.Value* @srl_val_nil()\n";
            } else if (lit->value.isBool()) {
                out_ << "    " << reg << " = call %struct.Value* @srl_val_bool(i32 " << (lit->value.asBool() ? 1 : 0) << ")\n";
            } else if (lit->value.isNumber()) {
                out_ << "    " << reg << " = call %struct.Value* @srl_val_num(double " << std::fixed << std::setprecision(6) << lit->value.asNumber() << ")\n";
            } else if (lit->value.isString()) {
                out_ << "    " << reg << " = call %struct.Value* @srl_val_nil()\n";
            } else {
                out_ << "    " << reg << " = call %struct.Value* @srl_val_nil()\n";
            }
            return reg;
        }

        case srl::ASTNodeType::VARIABLE_EXPR: {
            auto varExpr = static_cast<const srl::VariableExpr*>(expr);
            std::string reg = newRegister();
            out_ << "    " << reg << " = load %struct.Value*, %struct.Value** %" << varExpr->name.lexeme << ".ptr\n";
            return reg;
        }

        case srl::ASTNodeType::ASSIGN_EXPR: {
            auto assignExpr = static_cast<const srl::AssignExpr*>(expr);
            std::string valReg = emitExpr(assignExpr->value.get());
            out_ << "    store %struct.Value* " << valReg << ", %struct.Value** %" << assignExpr->name.lexeme << ".ptr\n";
            return valReg;
        }

        case srl::ASTNodeType::BINARY_EXPR: {
            auto bin = static_cast<const srl::BinaryExpr*>(expr);
            std::string leftReg = emitExpr(bin->left.get());
            std::string rightReg = emitExpr(bin->right.get());
            std::string resReg = newRegister();

            if (bin->op.lexeme == "+") {
                out_ << "    " << resReg << " = call %struct.Value* @srl_add(%struct.Value* " << leftReg << ", %struct.Value* " << rightReg << ")\n";
            } else if (bin->op.lexeme == "-") {
                out_ << "    " << resReg << " = call %struct.Value* @srl_sub(%struct.Value* " << leftReg << ", %struct.Value* " << rightReg << ")\n";
            } else if (bin->op.lexeme == "*") {
                out_ << "    " << resReg << " = call %struct.Value* @srl_mul(%struct.Value* " << leftReg << ", %struct.Value* " << rightReg << ")\n";
            } else if (bin->op.lexeme == "/") {
                out_ << "    " << resReg << " = call %struct.Value* @srl_div(%struct.Value* " << leftReg << ", %struct.Value* " << rightReg << ")\n";
            } else {
                out_ << "    " << resReg << " = call %struct.Value* @srl_val_nil()\n";
            }
            return resReg;
        }

        case srl::ASTNodeType::CALL_EXPR: {
            auto call = static_cast<const srl::CallExpr*>(expr);
            std::string resReg = newRegister();
            out_ << "    " << resReg << " = call %struct.Value* @srl_val_nil()\n";
            return resReg;
        }

        default:
            return "call %struct.Value* @srl_val_nil()";
    }
}

} // namespace srlc
